[versions]
androidPluginGradle = "8.0.1"
androidx-activity-compose = "1.7.1"
androidx-appcompat = "1.6.1"
androidx-compose = "1.4.2"
androidx-compose-compiler = "1.4.6"
androidx-compose-wear = "1.1.2"
androidx-core = "1.10.0"
androidx-datastore = "1.0.0"
androidx-lifecycle = "2.6.1"
androidx-wear = "1.2.0"
dagger-hilt = "2.46"
dagger-hilt-navigationCompose = "1.0.0"
logcat = "0.1"
kotlin = "1.8.20"
kotlin-coroutines = "1.6.4"
kotlinova = "3.0.0-alpha10"
playServices-wearable = "18.0.0"
versionsPlugin = "0.46.0"
wire = "4.6.0"

[libraries]
androidPluginGradle = { module = "com.android.tools.build:gradle", version.ref = "androidPluginGradle" }
androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "androidx-activity-compose" }
androidx-lifecycle-viewModel-compose = { module = " androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "androidx-lifecycle" }
androidx-lifecycle = { module = " androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "androidx-lifecycle" }
androidx-compose-compiler = { module = "androidx.compose.compiler:compiler", version.ref = "androidx-compose-compiler" }
androidx-compose-foundation = { module = "androidx.compose.foundation:foundation", version.ref = "androidx-compose" }
androidx-compose-material = { module = "androidx.compose.material:material", version.ref = "androidx-compose" }
androidx-compose-ui = { module = "androidx.compose.ui:ui", version.ref = "androidx-compose" }
androidx-compose-ui-tooling = { module = "androidx.compose.ui:ui-tooling", version.ref = "androidx-compose" }
androidx-compose-runtime = { module = "androidx.compose.runtime:runtime", version.ref = "androidx-compose" }
androidx-compose-wear-foundation = { module = "androidx.wear.compose:compose-foundation", version.ref = "androidx-compose-wear" }
androidx-compose-wear-material = { module = "androidx.wear.compose:compose-material", version.ref = "androidx-compose-wear" }
androidx-compose-wear-navigation = { module = "androidx.wear.compose:compose-navigation", version.ref = "androidx-compose-wear" }
androidx-core = { module = "androidx.core:core-ktx", version.ref = "androidx-core" }
androidx-datastore = { module = "androidx.datastore:datastore", version.ref = "androidx-datastore" }
androidx-appcompat = { module = "androidx.appcompat:appcompat", version.ref = "androidx-appcompat" }
androidx-wear = { module = "androidx.wear:wear", version.ref = "androidx-wear" }
dagger-hilt = { module = "com.google.dagger:hilt-android", version.ref = "dagger-hilt" }
dagger-hilt-pluginGradle = { module = "com.google.dagger:hilt-android-gradle-plugin", version.ref = "dagger-hilt" }
dagger-hilt-compiler = { module = "com.google.dagger:hilt-android-compiler", version.ref = "dagger-hilt" }
dagger-hilt-navigationCompose = { module = " androidx.hilt:hilt-navigation-compose ", version.ref = "dagger-hilt-navigationCompose" }
logcat = { module = "com.squareup.logcat:logcat", version.ref = "logcat" }
kotlin-pluginGradle = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
kotlin-coroutines = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlin-coroutines" }
kotlin-coroutines-playServices = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-play-services", version.ref = "kotlin-coroutines" }
kotlinova-gradle = { module = "si.inova.kotlinova:gradle", version.ref = "kotlinova" }
playServices-wearable = { module = "com.google.android.gms:play-services-wearable", version.ref = "playServices-wearable" }
versionsPlugin = { module = "com.github.ben-manes:gradle-versions-plugin", version.ref = "versionsPlugin" }
wire-runtime = { module = "com.squareup.wire:wire-runtime", version.ref = "wire" }
wire-pluginGradle = { module = "com.squareup.wire:wire-gradle-plugin", version.ref = "wire" }
