[versions]
androidPluginGradle = "7.0.3"
androidx-appcompat = "1.3.1"
androidx-core = "1.6.0"
kotlin = "1.5.31"

[libraries]
androidPluginGradle = { module = "com.android.tools.build:gradle", version.ref = "androidPluginGradle" }
androidx-core = { module = "androidx.core:core-ktx", version.ref = "androidx.core" }
androidx-appcompat = { module = "androidx.appcompat:appcompat", version.ref = "androidx.appcompat" }
kotlin-pluginGradle = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }