[versions]
androidPluginGradle = "7.0.3"
androidx-appcompat = "1.3.1"
androidx-core = "1.6.0"
androidx-wear = "1.2.0"
kotlin = "1.5.31"
playServices-wearable = "17.1.0"

[libraries]
androidPluginGradle = { module = "com.android.tools.build:gradle", version.ref = "androidPluginGradle" }
androidx-core = { module = "androidx.core:core-ktx", version.ref = "androidx.core" }
androidx-appcompat = { module = "androidx.appcompat:appcompat", version.ref = "androidx.appcompat" }
androidx-wear = { module = "androidx.wear:wear", version.ref = "androidx.wear" }
kotlin-pluginGradle = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
playServices-wearable = { module = "com.google.android.gms:play-services-wearable", version.ref = "playServices.wearable" }
